# Generated by Django 4.1.3 on 2022-11-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_availability_employee_availability_numberofhours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='numberOfHours',
            new_name='number_of_hours',
        ),
    ]
